model:
  model_dir: "models"
  model_path: "llama-3.1-8b-instruct.Q4_K_M.gguf"
  n_ctx: 4096
  n_threads: null
  n_gpu_layers: null
  use_mmap: true
  temperature: 0.7
  top_p: 0.95

memory:
  data_dir: "data"
  max_context_snippets: 6
  embed_model: "sentence-transformers/all-MiniLM-L6-v2"

identity:
  anchors_file: "src/identity/anchors.yaml"
  anchors_per_query: 2
  anchor_injection: "every_query"

web:
  # Domains that are allowed for URL fetching. Empty list allows none.
  allowed_domains:
    - example.com
  # Restrict fetched files to these extensions. Empty string allows URLs
  # without an explicit extension.
  allowed_file_extensions:
    - ""
    - .html
    - .txt
    - .pdf
